# Generated by Django 5.1.3 on 2024-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.IntegerField(max_length=10)),
                ('coreo_elec', models.CharField(max_length=150)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
    ]
