# Generated by Django 5.1.3 on 2024-12-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inven', models.IntegerField(primary_key=True, serialize=False)),
                ('id_comic', models.IntegerField()),
                ('cantidad_dispo', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=250)),
                ('fecha_entrada', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('id_tienda', models.IntegerField()),
            ],
        ),
    ]
