# Generated by Django 5.1.3 on 2024-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
